name: hop_client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/quiz_data.json
  fonts:
    - family: Murecho
      fonts:
        - asset: assets/fonts/Murecho/static/Murecho-Thin.ttf
          weight: 100
        - asset: assets/fonts/Murecho/static/Murecho-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Murecho/static/Murecho-Light.ttf
          weight: 300
        - asset: assets/fonts/Murecho/static/Murecho-Regular.ttf
          weight: 400
        - asset: assets/fonts/Murecho/static/Murecho-Medium.ttf
          weight: 500
        - asset: assets/fonts/Murecho/static/Murecho-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Murecho/static/Murecho-Bold.ttf
          weight: 700
        - asset: assets/fonts/Murecho/static/Murecho-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Murecho/static/Murecho-Black.ttf
          weight: 900
