name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Archive
        run: |
          cd ios
          xcodebuild archive -project Runner.xcodeproj -scheme Runner -archivePath Runner.xcarchive -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO

      - name: Create ExportOptions.plist
        run: |
          echo '${{ secrets.EXPORT_OPTIONS }}' > ios/ExportOptions.plist
          cat ios/ExportOptions.plist

      - name: Create Private Key
        run: |
          mkdir -p ios/private_keys
          echo -n '${{ secrets.APPLE_API_KEY_BASE64 }}' | base64 --decode > ios/private_keys/AuthKey_${{ secrets.APPLE_API_ISSUE_ID }}.p8

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive -archivePath Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./ -allowProvisioningUpdates -authenticationKeyPath `pwd`/private_keys/AuthKey_${{ secrets.APPLE_API_ISSUE_ID }}.p8 -authenticationKeyID ${{ secrets.APPLE_API_KEY_ID }} -authenticationKeyIssuerID ${{ secrets.APPLE_API_ISSUE_ID }}
          find ./ -name "*.ipa" -print

      - name: Upload to App Store Connect
        run: |
          xcrun altool --upload-app -f ios/hop_client.ipa -t ios -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APP_SPECIFIC_PASSWORD }} --type ios
